$(document).ready(function(){
    $("#fakeStoryPoint").click(function(){
		CKEDITOR.instances["editor1"].setData($('#fakeStoryPointText').val());
		$("#infoEditingForm").show();
    });
    $("#infoEditingFormClose").click(function(){
        $("#infoEditingForm").hide();
    });
});